Areas/Admin/Controllers/InvoiceController.cs
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Http;

using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using PharmacityStore.Models;
using PharmacityStore.Repository;
using System.Security.Claims;
using Microsoft.EntityFrameworkCore;
using System.Diagnostics;
using Microsoft.AspNetCore.Authorization;
using System.Data;

namespace PharmacityStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]
    public class InvoiceController : Controller
    {
        private readonly IInvoiceRepository _invoiceRepository;
        private IUserRepository _userRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public InvoiceController( IUserRepository userRepository,
            IInvoiceRepository invoiceRepository, IHttpContextAccessor httpContextAccessor)
        {
            _userRepository = userRepository;
            _invoiceRepository = invoiceRepository;
            _httpContextAccessor = httpContextAccessor;
        }

        public IActionResult ViewAllInvoice()
        {
           
            var q1 = from c in _userRepository.GetAll()
                     select new SelectListItem()
                     {
                         Text = c.UserId.ToString(),
                         Value = c.UserId.ToString(),
                     };

            ViewBag.UserId = q1.ToList();
            //1 get data
            List<Invoice> lst = _invoiceRepository.GetAll();
            //2 data to view
            return View("ViewAllInvoice", lst);
        }
        [HttpGet]
        public IActionResult CreateInvoice()
        {
           
            
            var q1 = from c in _userRepository.GetAll()
                     select new SelectListItem()
                     {
                         Text = c.UserId.ToString(),
                         Value = c.UserId.ToString(),
                     };

            ViewBag.UserId = q1.ToList();
            return View("CreateInvoice", new Invoice());
        }
        [HttpPost]
        public IActionResult SaveInvoice(Invoice invoice)
        {
            
                return View("CreateInvoice");
            
        }
        public IActionResult EditInvoice(Int16 id)
        {
           
            var q1 = from c in _userRepository.GetAll()
                     select new SelectListItem()
                     {
                         Text = c.UserId.ToString(),
                         Value = c.UserId.ToString(),
                     };
          

            ViewBag.UserId = q1.ToList();
            
            return View("EditInvoice", _invoiceRepository.FindById(id));
        }
        [HttpPost]
        public IActionResult UpdateInvoice(Invoice invoice)
        {
            if (ModelState.IsValid)
            {
                // Cập nhật trạng thái của hóa đơn
                switch (invoice.Status)
                {
                    case 0:
                        invoice.Status = 0;
                        break;
                    case 1:
                        invoice.Status = 1; ;
                        break;
                    case 2:
                        invoice.Status = 2; ;
                        break;
                    default:
                        break;
                }

                _invoiceRepository.Update(invoice); // Cập nhật hóa đơn trong cơ sở dữ liệu
                return RedirectToAction("ViewAllInvoice");
            }

            // Nếu dữ liệu không hợp lệ, quay trở lại trang sửa hóa đơn với dữ liệu hiện tại
            var q1 = from c in _userRepository.GetAll()
                     select new SelectListItem()
                     {
                         Text = c.UserId.ToString(),
                         Value = c.UserId.ToString(),
                     };

            ViewBag.UserId = q1.ToList();
            return View("EditInvoice", invoice);
        }

        public IActionResult Delete(Int16 invoiceId)
        {
           
            _invoiceRepository.Delete(invoiceId);
            return RedirectToAction("ViewAllInvoice");
        }
        public IActionResult DeleteInvoice(Int16 id)
        {
            return View("DeleteInvoice", _invoiceRepository.FindById(id));
        }
    }
}

Areas/Admin/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using PharmacityStore.Models;
using PharmacityStore.Repository;
using System.Diagnostics;
using System.Security.Claims;
using Microsoft.AspNetCore.Authentication.Cookies;
using Microsoft.AspNetCore.Authentication;
using Microsoft.AspNetCore.Authorization;

namespace PharmacityStore.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admin")]

    public class UserController : Controller
    {
        private IUserRepository _userRepository;
        private readonly IHttpContextAccessor _httpContextAccessor;
        public UserController(IUserRepository userRepository, IHttpContextAccessor httpContextAccessor)
        {
            _userRepository = userRepository;
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult ViewAllUser()
        {
           
            //1 get data
            List<User> lst = _userRepository.GetAll();
            //2 data to view
            return View("ViewAllUser", lst);
        }
        [HttpGet]
        public IActionResult CreateUser()
        {
           

            return View("CreateUser", new User());
        }
        [HttpPost]
        public IActionResult SaveUser(User user)
        {
            if (ModelState.IsValid)
            {
                bool isUserNameExist = _userRepository.checkname(user.UserName);
                if (isUserNameExist)
                {
                    ModelState.AddModelError(string.Empty, "tên đã có");
                    return View("CreateUser");
                }
                _userRepository.Create(user);

                return RedirectToAction("ViewAllUser");

            }
            else
            {
                return View("CreateUser");
            }
        }
        public IActionResult EditUser(Int16 id)
        {
            

            return View("EditUser", _userRepository.FindById(id));
        }
        [HttpPost]
        public IActionResult UpdateUser(User user)
        {

            if (ModelState.IsValid)
            {
                bool isUserNameExist = _userRepository.checkname(user.UserName);
                if (isUserNameExist)
                {
                    ModelState.AddModelError(string.Empty, "tên đã có");
                    return View("EditUser");


                }
                _userRepository.Update(user);

                return RedirectToAction("ViewAllUser");

            }
            else
            {
                return View("EditUser");
            }
        }
        
        public IActionResult Delete(Int16 userId)
        {
           
            _userRepository.Delete(userId);
            return RedirectToAction("ViewAllUser");
        }
        public IActionResult DeleteUser(Int16 id)
        {
            return View("DeleteUser", _userRepository.FindById(id));
        }
      
        [HttpGet]
        public IActionResult Logout()
        {
           
            HttpContext.SignOutAsync(); // Đăng xuất người dùng

            return RedirectToAction("Login", "Home");
        }

    }
}

Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using PharmacityStore.Models;
using PharmacityStore.Repository;
using System.Diagnostics;
namespace PharmacityStore.Controllers
{
    public class ProductController : Controller
    {
        private PharmacityContext _ctx;
        private readonly IProductRepository _productRepository;

        public ProductController( IProductRepository productRepository, PharmacityContext ctx)
        {
            _ctx = ctx;
            _productRepository = productRepository;
        }

        public IActionResult Index()
        {
            //1.Call dao
            List<Product> ds = _productRepository.SortProductsByPriceDescending();
            //2.passing data
            return View(ds);
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Views/Shared/_AdminLayout.cshtml
    <!DOCTYPE html>
    <html lang="en">

    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <title>Admin</title>

        <!-- Favicon -->
        <link rel="shortcut icon" href="~/~/Adminassets/images/logo/favicon.png">

        <!-- page css -->

        <!-- Core css -->
        <link href="~/Adminassets/css/app.min.css" rel="stylesheet">

    </head>

    <body>
        <div class="app">
            <div class="layout">
                <!-- Header START -->
                <div class="header">
                    <div class="logo logo-dark">
                        <a href="/admin">
                            <img style="
                                 width: 100%;" src="~/img/logo.svg" alt="Logo">
                            <img class="logo-fold" src="~/Adminassets/images/logo/logo-fold.png" alt="Logo">
                        </a>
                    </div>
                   
                    <div class="nav-wrap">
                        <ul class="nav-left">
                            <li class="desktop-toggle">
                                <a href="javascript:void(0);">
                                    <i class="anticon"></i>
                                </a>
                            </li>
                            <li class="mobile-toggle">
                                <a href="javascript:void(0);">
                                    <i class="anticon"></i>
                                </a>
                            </li>
                            
                        </ul>
                        <ul class="nav-right">
                            <li class="dropdown dropdown-animated scale-left">
                                <a href="javascript:void(0);" data-toggle="dropdown">
                                    <i class="anticon anticon-bell notification-badge"></i>
                                </a>
                                <div class="dropdown-menu pop-notification">
                                    <div class="p-v-15 p-h-25 border-bottom d-flex justify-content-between align-items-center">
                                        <p class="text-dark font-weight-semibold m-b-0">
                                            <i class="anticon anticon-bell"></i>
                                            <span class="m-l-10">Notification</span>
                                        </p>
                                        <a class="btn-sm btn-default btn" href="javascript:void(0);">
                                            <small>View All</small>
                                        </a>
                                    </div>
                                    <div class="relative">
                                        <div class="overflow-y-auto relative scrollable" style="max-height: 300px">
                                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                                <div class="d-flex">
                                                    <div class="avatar avatar-blue avatar-icon">
                                                        <i class="anticon anticon-mail"></i>
                                                    </div>
                                                    <div class="m-l-15">
                                                        <p class="m-b-0 text-dark">You received a new message</p>
                                                        <p class="m-b-0"><small>8 min ago</small></p>
                                                    </div>
                                                </div>
                                            </a>
                                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                                <div class="d-flex">
                                                    <div class="avatar avatar-cyan avatar-icon">
                                                        <i class="anticon anticon-user-add"></i>
                                                    </div>
                                                    <div class="m-l-15">
                                                        <p class="m-b-0 text-dark">New user registered</p>
                                                        <p class="m-b-0"><small>7 hours ago</small></p>
                                                    </div>
                                                </div>
                                            </a>
                                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 border-bottom">
                                                <div class="d-flex">
                                                    <div class="avatar avatar-red avatar-icon">
                                                        <i class="anticon anticon-user-add"></i>
                                                    </div>
                                                    <div class="m-l-15">
                                                        <p class="m-b-0 text-dark">System Alert</p>
                                                        <p class="m-b-0"><small>8 hours ago</small></p>
                                                    </div>
                                                </div>
                                            </a>
                                            <a href="javascript:void(0);" class="dropdown-item d-block p-15 ">
                                                <div class="d-flex">
                                                    <div class="avatar avatar-gold avatar-icon">
                                                        <i class="anticon anticon-user-add"></i>
                                                    </div>
                                                    <div class="m-l-15">
                                                        <p class="m-b-0 text-dark">You have a new update</p>
                                                        <p class="m-b-0"><small>2 days ago</small></p>
                                                    </div>
                                                </div>
                                            </a>
                                        </div>
                                    </div>
                                </div>
                            </li>
                            <li class="dropdown dropdown-animated scale-left">
                                <div class="pointer" data-toggle="dropdown">
                                    <div class="avatar avatar-image  m-h-10 m-r-15">
                                        <img src="~/Adminassets/images/avatars/thumb-3.jpg"  alt="">
                                    </div>
                                </div>
                                <div class="p-b-15 p-t-20 dropdown-menu pop-profile">
                                    <div class="p-h-20 p-b-15 m-b-10 border-bottom">
                                        <div class="d-flex m-r-50">
                                            <div class="avatar avatar-lg avatar-image">
                                                <img src="~/Adminassets/images/avatars/thumb-3.jpg" alt="">
                                            </div>
                                            <div class="m-l-10">
                                                <p class="m-b-0 text-dark font-weight-semibold">Marshall Nichols</p>
                                                <p class="m-b-0 opacity-07">UI/UX Desinger</p>
                                            </div>
                                        </div>
                                    </div>
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div>
                                                <i class="anticon opacity-04 font-size-16 anticon-user"></i>
                                                <span class="m-l-10">Edit Profile</span>
                                            </div>
                                            <i class="anticon font-size-10 anticon-right"></i>
                                        </div>
                                    </a>
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div>
                                                <i class="anticon opacity-04 font-size-16 anticon-lock"></i>
                                                <span class="m-l-10">Account Setting</span>
                                            </div>
                                            <i class="anticon font-size-10 anticon-right"></i>
                                        </div>
                                    </a>
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div>
                                                <i class="anticon opacity-04 font-size-16 anticon-project"></i>
                                                <span class="m-l-10">Projects</span>
                                            </div>
                                            <i class="anticon font-size-10 anticon-right"></i>
                                        </div>
                                    </a>
                                    <a href="javascript:void(0);" class="dropdown-item d-block p-h-15 p-v-10">
                                        <div class="d-flex align-items-center justify-content-between">
                                            <div>
                                                <i class="anticon opacity-04 font-size-16 anticon-logout"></i>
                                                <span class="m-l-10">Logout</span>
                                            </div>
                                            <i class="anticon font-size-10 anticon-right"></i>
                                        </div>
                                    </a>
                                </div>
                            </li>
                          
                        </ul>
                    </div>
                </div>    
                <!-- Header END -->

                <!-- Side Nav START -->
               
                @await Html.PartialAsync("_SideNavPartialView")
            
            <!-- Side Nav END -->

                <!-- Page Container START -->
                <div class="page-container">


                    <!-- Content Wrapper START -->
                    <div class="main-content">
                   
                        @RenderBody()
                    
                   
                       
                    </div>
                    <!-- Content Wrapper END -->

                    <!-- Footer START -->
                   
                    <!-- Footer END -->

                </div>
                <!-- Page Container END -->

               

               
            </div>
        </div>
       

        <!-- Core Vendors JS -->
        <script src="~/Adminassets/js/vendors.min.js"></script>

        <!-- page js -->
        <script src="~/Adminassets/vendors/chartjs/Chart.min.js"></script>
        <script src="~/Adminassets/js/pages/dashboard-default.js"></script>

        <!-- Core JS -->
        <script src="~/Adminassets/js/app.min.js"></script>

        @await RenderSectionAsync("Scripts",required: false)

    </body>

    </html>

Views/Shared/_SideNavPartialView.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<div class="side-nav ">
    <div class="side-nav-inner">
        <ul class="side-nav-menu scrollable">
            <li class="nav-item ">
                <a class="dropdown-toggle"   asp-controller="Home" asp-action="Index">
                    <span class="icon-holder">
                        <i class="anticon anticon-dashboard"></i>
                    </span>
                    <span class="title ">Dashboard</span>
                    <span class="arrow">
                        <i class="arrow-icon"></i>
                    </span>
                </a>
               
            </li>
            
           
            <li class="nav-item dropdown">
                <a class="dropdown-toggle" href="javascript:void(0);">
                    <span class="icon-holder">
                        <i class="anticon anticon-hdd"></i>
                    </span>
                    <span class="title" <a asp-controller="Home" asp-action="Index">System Manager </a></span> 
                    <p class="arrow" style="top:12px">
                        <i class="arrow-icon"></i>
                    </p>
                </a>
                <ul class="dropdown-menu">
                    <li>
                        <a   asp-controller="Product" asp-action="ViewAllProduct">Product Manager</a>
                    </li>
                    <li>
                        <a asp-controller="User" asp-action="ViewAllUser">User Manager</a>
                    </li>
                    <li>
                        <a asp-controller="Home" asp-action="ViewAllCategories">Category Manager</a>
                    </li>
                    <li>
                        <a asp-controller="Invoice" asp-action="ViewAllInvoice">Invoice Manager</a>
                    </li>
                </ul>
            </li>
            <li><a asp-controller="User" asp-action="Logout" asp-area="Admin" class="nav-link">Logout</a></li>
         
        </ul>
    </div>
</div>